-- Add specific_location_type column to locations table
-- This provides a more granular categorization (e.g., "Hotel", "Laundry", "Bank")
-- while location_type holds the broader category (e.g., "Business", "Residence")
ALTER TABLE detectives.locations
ADD COLUMN specific_location_type TEXT;

-- Add comment for documentation
COMMENT ON COLUMN detectives.locations.specific_location_type IS 'Specific sub-type of location (e.g., Hotel, Laundry, Bank) within the broader location_type category';

-- Change activities.id from user-supplied INTEGER to auto-generated SERIAL
-- so datasets without pre-assigned IDs can be loaded
ALTER TABLE detectives.activities
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Advance the identity sequence past any existing IDs
SELECT setval(
    pg_get_serial_sequence('detectives.activities', 'id'),
    COALESCE((SELECT MAX(id) FROM detectives.activities), 0)
);
