# Show available recipes
default:
    @just --list

# Serve the preview site with Hugo
serve:
    @echo "Serving the preview site with Hugo ..."
    hugo serve --buildDrafts --buildFuture --disableFastRender

# Build the dev site with Hugo
build:
    @echo "\nBuilding the dev site with Hugo ..."
    hugo --cleanDestinationDir --buildDrafts --buildFuture --baseURL https://mappingpinkertons.rrchnm.org/
    @echo "Website finished building."

# Build the production site with Hugo
build-prod:
    @echo "\nBuilding the prod site with Hugo ..."
    hugo --cleanDestinationDir --minify --baseURL https://mappingpinkertons.rrchnm.org/
    @echo "Website finished building."

# Build the Tailwind CSS
tailwind:
    @echo "\nBuilding the tailwind css ..."
    cd themes/pinkertons && npm run build-tw
    @echo "Tailwind css finished building."
